### ISSUE TITLE
AIs can roll Traitor instead of Malf, for.. some reason.

### ISSUE THREAD

**Issue by lessthnthree** [effigy-se/effigy-se#112]
![image](https://github.com/effigy-se/effigy-se/assets/83487515/7bb3a551-958d-4eea-a284-76e03a85f23c)

**Comment by unit0016** [comment]
That'sss the wrong antag datum, and I'm willing to bet this wasn't a natural roll and was user error from whoever added it to the AI.

**Comment by unit0016** [comment]
Got it confirmed this was natural and not through fucking with the add antag datum menu.
![image](https://github.com/effigy-se/effigy-se/assets/50649185/7fdc6f28-3561-49d7-8541-0d68dcf0b729)

**Comment by lessthnthree** [comment]
I can't replicate this rolling in test. Given we've had a bunch of updates since, re-open if its still happening.
