### ISSUE TITLE
Uniform slot doesn't show equipped item

### ISSUE THREAD

**Issue by lessthnthree** [effigy-se/effigy-se#30]
![image](https://user-images.githubusercontent.com/83487515/236269197-aab2af8d-b25a-4760-9e4b-ff5cef783a7b.png)

**Comment by unit0016** [comment]
Can replicate this with every equip slot + backpacks. Something related to how HUDs draw items is fucky.

**Comment by lessthnthree** [comment]
Fixed by #34
