### ISSUE TITLE
Parallax turns white when dying and getting revived with night vision mesons on

### ISSUE THREAD

**Issue by distributivgesetz** [effigy-se/effigy-se#483]
## Round ID:

[222247](https://scrubby.melonmesa.com/round/222247)-2236

## Testmerges: 

- [Discord to Effigy ahelps](https://www.github.com/effigy-se/effigy-se/pull/403)

### Original Report:

> Reporting client: chrapacz2000/(\<name omitted\>)
Reporting client version: 514.1589
Time Dilation: 0% (Average: 0% / 0% / 0%)
Map: FoxHoleStation
Round ID: [222247](https://scrubby.melonmesa.com/round/222247)-2236
Server Rev: 53978e4
Server Time: 2023-08-28 18:38:49
World Time: 78539
Round Time: 02:11:39
Adj. Round Time: 01:24:46
> 
> night vision meson glitch
if you die while wearing NV meson goggles and you get revived, your paralax will become white and if you take off the goggles it will make everything translucent

This could be an upstream bug, possibly related to https://www.github.com/tgstation/tgstation/issues/71757. I could not reproduce this myself sadly. Still leaving it here though.

**Comment by unit0016** [comment]
No longer an issue outside of ghost orbitting; which is known upstream already.
