### ISSUE TITLE
Mining suit voucher redemption is not implemented into mining vendor `attackby`

### ISSUE THREAD

**Issue by distributivgesetz** [effigy-se/effigy-se#484]
## Round ID:

N/A

## Issue/Reproduction:

The mining suit voucher file in `local\code\modules\mining\suit_voucher.dm` implements a proc onto the mining vendor that handles redeeming vouchers, however the proc is unused, likely due to a merge oversight.

![image](https://github.com/effigy-se/effigy-se/assets/47710522/705b8e4d-e5c7-4305-a8ae-96cc2f528c94)

**Comment by unit0016** [comment]
~~Honestly I dislike the SEVA to the point where I don't mind this anyways~~

**Comment by unit0016** [comment]
#764
