### ISSUE TITLE
Changeling midround screenshot test fails

### ISSUE THREAD

**Issue by lessthnthree** [effigy-se/effigy-se#500]
Fails since https://github.com/effigy-se/effigy-se/pull/497

Probably due to changeling sting.

--
Related to #471

**Comment by distributivgesetz** [comment]
I disabled the workflow that posts the comment for the time being to make PRs cleaner, a maintainer will have to go and reenable it once this issue is fixed.

**Comment by lessthnthree** [comment]
Sure
