### ISSUE TITLE
Rimpoint: HoP bed has elevator music

### ISSUE THREAD

**Issue by lessthnthree** [effigy-se/effigy-se#607]
## Issue/Reproduction:

Be on the tile with the HoP's bed, not the best choice for lovemaking music.

**Comment by unit0016** [comment]
https://github.com/effigy-se/effigy-se/assets/50649185/6a73adde-08b6-47af-9519-b3e054f97814

**Comment by lessthnthree** [comment]
https://github.com/effigy-se/effigy-se/pull/671
