### ISSUE TITLE
Mobs layer under glass floors.

### ISSUE THREAD

**Issue by unit0016** [effigy-se/effigy-se#83]
![image](https://github.com/effigy-se/effigy-se/assets/50649185/db351be4-2a7a-4f91-8667-27651d5abdc5)

**Comment by unit0016** [comment]
Might be deprecated with sidemap being fixed?? Need to check.

**Comment by unit0016** [comment]
This one's back, saw it on a large character under a reinforced glass floor.

**Comment by lessthnthree** [comment]
SR has this too.

**Comment by unit0016** [comment]
> Upstream!

**[EXTREMELY LOUD INCORRECT BUZZER]**
![image](https://github.com/effigy-se/effigy-se/assets/50649185/bee75a0c-70ee-4819-9ee6-58ea7ac3834a)

**Comment by unit0016** [comment]
In all seriousness though yeah I don't think this is upstream. Campbell may be incredibly out of date (IT'S STILL ADVERTISING MAPPING MARCH __WHAT__) but glancing at Bagil too, I don't think I saw it there.
