### ISSUE TITLE
Quirk points TGUI-Side only go down.

### ISSUE THREAD

**Issue by unit0016** [effigy-se/effigy-se#90]
On the backend they're the correct number, TGUI will refresh if you add in more positive quirks than you can actually afford - but the number's still wrong.

**Comment by lessthnthree** [comment]
Is this still an issue since https://github.com/effigy-se/effigy-se/pull/116?

**Comment by unit0016** [comment]
Unable to check until live updates, as that's where the character with the "ghost quirks" is hosted and I don't have a local copy to confirm. *Probably* is fixed, though.

**Comment by lessthnthree** [comment]
Live updated a few hours ago.

**Comment by unit0016** [comment]
Can confirm it's still an issue.
